title: kuberollouttrigger
description: "A lightweight GitHub Actions OIDC authenticated webhook and in-cluster worker that automatically restarts matching Kubernetes Deployments when a container image tag is updated."

remote_theme: just-the-docs/just-the-docs@v0.12.0
plugins:
  - jekyll-remote-theme

# Aux links for the upper right navigation
aux_links:
  "kuberollouttrigger on GitHub":
    - "https://github.com/UnitVectorY-Labs/kuberollouttrigger/"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/UnitVectorY-Labs/kuberollouttrigger/"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"
